# Establece la imagen base para el frontend
FROM node:latest AS builder

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de configuración y dependencias del proyecto al contenedor
COPY package.json package-lock.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el código fuente del frontend al contenedor
COPY . /app/

# Construye la aplicación frontend
RUN npm run build

# Etapa final
FROM nginx:latest

# Copia los archivos estáticos del frontend generados en la etapa anterior al directorio de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia el archivo de configuración de Nginx personalizado al contenedor
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expone el puerto en el que Nginx está escuchando
EXPOSE 5173

# Comando por defecto para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
